In [2]:
import numpy as np

from sklearn.model_selection import train_test_split

In [3]:
fakedata = np.tile(np.array([1, 2, 3, 4]), (10,1)) + np.tile(10*np.arange(1,11),(4,1)).T
fakelabels = np.arange(10)>4
print(fakedata)
print()
print(fakelabels)

[[ 11  12  13  14]
 [ 21  22  23  24]
 [ 31  32  33  34]
 [ 41  42  43  44]
 [ 51  52  53  54]
 [ 61  62  63  64]
 [ 71  72  73  74]
 [ 81  82  83  84]
 [ 91  92  93  94]
 [101 102 103 104]]

[False False False False False  True  True  True  True  True]


In [17]:
partitions = [.8, .1, .1]

train_data, testTMP_data, train_labels, testTMP_labels = \
train_test_split(fakedata, fakelabels, train_size=partitions[0])

split = partitions[1] / np.sum(partitions[1:])
devset_data, test_data, devset_labels, test_labels = \
train_test_split(testTMP_data, testTMP_labels, train_size=split)

print('Training data size:', str(train_data.shape))
print('Devset data size:', str(devset_data.shape))
print('test data size:', str(test_data.shape))

print('Training data'), print(' ')
print(train_data)

print('Devset data'), print(' ')
print(devset_data)

print(' data'), print(' ')
print(test_data)

Training data size: (8, 4)
Devset data size: (1, 4)
test data size: (1, 4)
Training data
 
[[ 51  52  53  54]
 [ 41  42  43  44]
 [ 91  92  93  94]
 [ 11  12  13  14]
 [ 71  72  73  74]
 [101 102 103 104]
 [ 61  62  63  64]
 [ 81  82  83  84]]
Devset data
 
[[31 32 33 34]]
 data
 
[[21 22 23 24]]


In [21]:
partitions = np.array([.8, .1, .1])

partitionBnd = np.cumsum(partitions*len(fakelabels)).astype(int)

randindices = np.random.permutation(range(len(fakelabels)))

In [23]:
train_dataN = fakedata[randindices[:partitionBnd[0]],:]
train_labelsN = fakelabels[randindices[:partitionBnd[0]]]

devset_dataN = fakedata[randindices[partitionBnd[0]:partitionBnd[1]],:]
devset_labelsN = fakelabels[randindices[partitionBnd[0]:partitionBnd[1]]]

test_dataN = fakedata[randindices[partitionBnd[1]:],:]
test_labelsN = fakelabels[randindices[partitionBnd[1]:]]

In [26]:
print('Training data size', str(train_dataN.shape))
print('Devset size:', str(devset_dataN.shape))
print('Test data size', str(test_dataN.shape))
print(' ')

print('Training data:')
print(train_dataN)
print(' ')

print('Devset data:')
print(devset_dataN)
print(' ')

print('Test data:')
print(test_dataN)
print(' ')

Training data size (8, 4)
Devset size: (1, 4)
Test data size (1, 4)
 
Training data:
[[ 11  12  13  14]
 [ 41  42  43  44]
 [ 81  82  83  84]
 [ 21  22  23  24]
 [101 102 103 104]
 [ 31  32  33  34]
 [ 51  52  53  54]
 [ 91  92  93  94]]
 
Devset data:
[[61 62 63 64]]
 
Test data:
[[71 72 73 74]]
 
