# Matrix Multiplication

## Import 

In [1]:
import numpy as np
import torch

## Using numpy

In [4]:
A = np.random.randn(3, 4)
B = np.random.randn(4, 5)
C = np.random.randn(3, 7)

# np.matmul(A,B) = A@B
print(np.round(A@B, 2)), print(' ')
print(np.round(C.T@A, 2)), print(' ')

[[ 0.9   0.49  0.42  0.22  0.86]
 [ 0.38  0.53  0.83 -0.19 -0.07]
 [ 1.35  4.29  2.27 -4.25  1.88]]
 
[[ 0.52  0.25  1.08  1.44]
 [-0.47 -0.   -0.16 -0.2 ]
 [ 0.78  1.95  3.18 -0.75]
 [-1.13 -1.71 -2.41  1.79]
 [ 0.59  0.96  1.51 -0.6 ]
 [-0.79 -0.17 -0.52 -0.28]
 [ 1.37  0.74  1.81  0.82]]
 


(None, None)

## Using pytorch

In [8]:
A = torch.randn(3, 4)
B = torch.randn(4, 5)
C1 = np.random.randn(4, 7)
C2 = torch.tensor(C1, dtype=torch.float)

print(np.round(A@B, 2)), print(' ')
print(np.round(A@C1, 2)), print(' ')
print(np.round(A@C2, 2)), print(' ')

tensor([[ 0.1100,  1.0100, -2.6900,  0.9200, -2.4200],
        [-3.7700,  2.0400,  1.5500,  0.6300,  0.7700],
        [ 0.1600, -0.2900, -0.1700,  0.0600,  0.2500]])
 
tensor([[ 3.1300, -0.5900,  1.8300, -0.9200,  1.9400,  2.7600, -2.3600],
        [ 2.6800,  2.6800,  4.5600, -2.1900,  4.5500,  0.1600,  2.4000],
        [ 0.3100, -0.2700, -0.1600, -0.5100, -0.5000,  0.6400, -0.5700]],
       dtype=torch.float64)
 
tensor([[ 3.1300, -0.5900,  1.8300, -0.9200,  1.9400,  2.7600, -2.3600],
        [ 2.6800,  2.6800,  4.5600, -2.1900,  4.5500,  0.1600,  2.4000],
        [ 0.3100, -0.2700, -0.1600, -0.5100, -0.5000,  0.6400, -0.5700]])
 


/tmp/ipykernel_13859/3388610149.py:7: DeprecationWarning: __array_wrap__ must accept context and return_scalar arguments (positionally) in the future. (Deprecated NumPy 2.0)
  print(np.round(A@C1, 2)), print(' ')


(None, None)