# Min/Max & Argmin/Argmax

In [1]:
import numpy as np
import torch
import torch.nn as nn

## numpy

In [2]:
v = np.array([1, 40, 2, -3])

minval = np.min(v)
maxval = np.max(v)

print(f"Min: {minval}, Max: {maxval}")

minidx = np.argmin(v)
maxidx = np.argmax(v)

print(f"Argmin: {minidx}, Argmax: {maxidx}")

Min: -3, Max: 40
Argmin: 3, Argmax: 1


In [7]:
M = np.array([
    [0, 1, 10],
    [20, 8, 5]
])

print(M), print()

minvals1 = np.min(M)
minvals2 = np.min(M, axis=0)
minvals3 = np.min(M, axis=1)

print(minvals1)
print(minvals2)
print(minvals3)

[[ 0  1 10]
 [20  8  5]]

0
[0 1 5]
[0 5]


In [8]:
minidx1 = np.argmin(M)
minidx2 = np.argmin(M, axis=0)
minidx3 = np.argmin(M, axis=1)

print(M), print()
print(minidx1)
print(minidx2)
print(minidx3)

[[ 0  1 10]
 [20  8  5]]

0
[0 0 1]
[0 2]


## pytorch

In [14]:
v = torch.tensor([1, 40, 2, -3])

minval = torch.min(v)
maxval = torch.max(v)

print(f"Min: {minval}, Max: {maxval}")

minidx = torch.argmin(v)
maxidx = torch.argmax(v)

print(f"Argmin: {minidx}, Argmax: {maxidx}")

Min: -3, Max: 40
Argmin: 3, Argmax: 1


In [15]:
M = torch.tensor([
    [0, 1, 10],
    [20, 8, 5]
])

print(M), print()

min1 = torch.min(M)
min2 = torch.min(M, axis=0)
min3 = torch.min(M, axis=1)

print(min1), print()
print(min2), print()
print(min2.values), print()
print(min2.indices), print()
print(min3)

tensor([[ 0,  1, 10],
        [20,  8,  5]])

tensor(0)

torch.return_types.min(
values=tensor([0, 1, 5]),
indices=tensor([0, 0, 1]))

tensor([0, 1, 5])

tensor([0, 0, 1])

torch.return_types.min(
values=tensor([0, 5]),
indices=tensor([0, 2]))
