# Random

## numpy

In [2]:
import numpy as np

In [7]:
np.random.randint(50)

49

In [19]:
np.random.seed(17)
np.random.randint(50)

47

In [20]:
randseed1 = np.random.RandomState(17)
randseed2 = np.random.RandomState(200)

print(randseed1.randn(5))
print(randseed1.randn(5))
print(randseed2.randn(5))
print(randseed1.randn(5))

[ 0.27626589 -1.85462808  0.62390111  1.14531129  1.03719047]
[ 1.88663893 -0.11169829 -0.36210134  0.14867505 -0.43778315]
[-1.45094825  1.91095313  0.71187915 -0.24773829  0.36146623]
[ 2.171257    1.15231025 -1.81881234 -0.13804934  0.53983961]


## pytorch

In [21]:
import torch

In [22]:
torch.randn(5)

tensor([-1.0706,  0.3968,  0.3152, -0.1032, -0.1293])

In [31]:
torch.manual_seed(10)
print(torch.randn(5))

print(np.random.randn(5))

tensor([-0.6014, -1.0122, -0.3023, -1.2277,  0.9198])
[-0.59201441  0.65186419 -0.46234494 -1.98540219 -0.57283034]
