In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [62]:
prob = .25

dropout = nn.Dropout(p=prob)

x = torch.ones(10)

y = dropout(x)
print(x)
print(y)
print(torch.mean(y))

nodes = []
for i in range(10):
    if y[i] == 0:
        nodes.append('0')
    else:
        nodes.append('Node')
print(nodes)

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
tensor([1.3333, 0.0000, 1.3333, 1.3333, 0.0000, 1.3333, 1.3333, 0.0000, 0.0000,
        0.0000])
tensor(0.6667)
['Node', '0', 'Node', 'Node', '0', 'Node', 'Node', '0', '0', '0']


In [63]:
dropout.eval()

y = dropout(x)

print(y)
print(torch.mean(y))

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
tensor(1.)


In [75]:
y = F.dropout(x, training=False) # bool -> self.istraining

print(y)
print(torch.mean(y))

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
tensor(1.)


In [83]:
dropout.train()
y = dropout(x)
print(y)

dropout.eval()
y = dropout(x)
print(y)

#dropout.train()
y = dropout(x)
print(y)

tensor([0.0000, 0.0000, 1.3333, 1.3333, 0.0000, 1.3333, 0.0000, 1.3333, 1.3333,
        1.3333])
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
