In [9]:
import numpy as np
import torch
from torch.utils.data import TensorDataset, DataLoader

In [2]:
nObservations = 100
nFeatures = 20

data = np.random.randn(nObservations, nFeatures)

In [4]:
dataT = torch.tensor( data )

print('Numpy data:')
print(type(data))
print(data.shape)
print(data.dtype)
print(' ')

print('Tensor data')
print(type(dataT))
print(dataT.size())
print(dataT.dtype)
print(' ')

Numpy data:
<class 'numpy.ndarray'>
(100, 20)
float64
 
Tensor data
<class 'torch.Tensor'>
torch.Size([100, 20])
torch.float64
 


In [5]:
dataT2 = torch.tensor( data ).float()
print(dataT2.dtype)

dataT3 = torch.tensor( data ).long()
print(dataT3.dtype)

torch.float32
torch.int64


In [13]:
dataset = TensorDataset( dataT )
dataset.tensors

(tensor([[ 0.7107,  3.6058,  0.1090,  ...,  0.1918, -0.9204,  1.1981],
         [-0.7958, -0.3910, -0.3174,  ..., -0.3277,  1.4279,  1.1721],
         [-1.3655,  0.2424, -1.5569,  ..., -0.1394, -0.1891, -0.0039],
         ...,
         [-0.6266,  1.4077,  1.6284,  ..., -1.6738, -0.0814, -0.9750],
         [ 1.2238,  0.6853,  1.2689,  ...,  2.7746, -1.2660, -2.7454],
         [ 0.6104,  0.4485,  0.5408,  ..., -1.3610, -0.4943,  0.3934]],
        dtype=torch.float64),)

In [17]:
labels = torch.ceil(torch.linspace(.01,4,nObservations))

labels = labels.reshape((len(labels),1))

dataset = TensorDataset(dataT, labels)
print( dataset.tensors[0].size() )
print( dataset.tensors[1].size() )

print( np.shape(np.random.randint(5,size=nObservations)) )

torch.Size([100, 20])
torch.Size([100, 1])
(100,)


## DataLoaders

In [18]:
batchsize = 25
dataloader = DataLoader(dataset, batch_size=batchsize)

dataloader.dataset.tensors[0].size()

torch.Size([100, 20])

In [19]:
for dat, labs in dataloader:
    print('BATCH INFO:')
    print(dat.size())
    print(labs.size())
    print(' ')

BATCH INFO:
torch.Size([25, 20])
torch.Size([25, 1])
 
BATCH INFO:
torch.Size([25, 20])
torch.Size([25, 1])
 
BATCH INFO:
torch.Size([25, 20])
torch.Size([25, 1])
 
BATCH INFO:
torch.Size([25, 20])
torch.Size([25, 1])
 


In [20]:
for dat, labs in dataloader:
    print(labs.T)
    print(' ')

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1.]])
 
tensor([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
         2., 2., 2., 2., 2., 2., 2.]])
 
tensor([[3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
         3., 3., 3., 3., 3., 3., 3.]])
 
tensor([[4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
         4., 4., 4., 4., 4., 4., 4.]])
 


In [22]:
# DataLoader gets re-shuffle every time
dataloader = DataLoader(dataset, batch_size=batchsize, shuffle=True)
for dat, labs in dataloader:
    print(labs.T)
    print(' ')

tensor([[4., 2., 4., 1., 4., 4., 4., 1., 2., 1., 3., 4., 1., 1., 1., 3., 3., 3.,
         4., 1., 3., 2., 3., 3., 2.]])
 
tensor([[2., 4., 4., 3., 1., 2., 1., 1., 1., 3., 2., 2., 2., 2., 3., 2., 4., 2.,
         1., 4., 4., 3., 1., 1., 1.]])
 
tensor([[1., 2., 3., 2., 1., 2., 3., 4., 4., 1., 2., 3., 1., 4., 2., 2., 2., 4.,
         4., 2., 1., 3., 3., 2., 1.]])
 
tensor([[1., 3., 2., 3., 3., 1., 3., 3., 1., 4., 4., 3., 4., 4., 1., 3., 2., 4.,
         2., 4., 4., 3., 2., 4., 3.]])
 


In [ ]:
dat, labs = next(iter(dataloader))

labs