In [1]:
import numpy as np
import torch
import torch.nn as nn

In [2]:
widenet = nn.Sequential(
    nn.Linear(2,4),
    nn.Linear(4,3)
)

deepnet = nn.Sequential(
    nn.Linear(2,2),
    nn.Linear(2,2),
    nn.Linear(2,3)
)

print(widenet)
print(' ')
print(deepnet)

Sequential(
  (0): Linear(in_features=2, out_features=4, bias=True)
  (1): Linear(in_features=4, out_features=3, bias=True)
)
 
Sequential(
  (0): Linear(in_features=2, out_features=2, bias=True)
  (1): Linear(in_features=2, out_features=2, bias=True)
  (2): Linear(in_features=2, out_features=3, bias=True)
)


In [3]:
for p in deepnet.named_parameters():
    print(p)
    print(' ')

('0.weight', Parameter containing:
tensor([[ 0.0438, -0.0289],
        [ 0.4812,  0.6437]], requires_grad=True))
 
('0.bias', Parameter containing:
tensor([ 0.3261, -0.3775], requires_grad=True))
 
('1.weight', Parameter containing:
tensor([[ 0.0217,  0.6043],
        [-0.7059, -0.2236]], requires_grad=True))
 
('1.bias', Parameter containing:
tensor([-0.2630,  0.0500], requires_grad=True))
 
('2.weight', Parameter containing:
tensor([[-0.7025, -0.3981],
        [-0.5158,  0.5314],
        [-0.3451,  0.3239]], requires_grad=True))
 
('2.bias', Parameter containing:
tensor([ 0.4640, -0.1736,  0.0104], requires_grad=True))
 


In [6]:
for p in widenet.parameters():
    print(p)
    print(' ')

Parameter containing:
tensor([[ 0.1691,  0.1384],
        [ 0.6771, -0.3329],
        [-0.0799,  0.5852],
        [ 0.1432, -0.0636]], requires_grad=True)
 
Parameter containing:
tensor([-0.2176,  0.1090, -0.5353, -0.6498], requires_grad=True)
 
Parameter containing:
tensor([[-0.2573,  0.0372,  0.2070,  0.3803],
        [ 0.3388, -0.3917, -0.2576, -0.4606],
        [-0.1228,  0.4095, -0.2294,  0.3957]], requires_grad=True)
 
Parameter containing:
tensor([-0.0544,  0.3365,  0.1241], requires_grad=True)
 


In [5]:
numNodesInWide = 0
for p in widenet.named_parameters():
    if 'bias' in p[0]:
        numNodesInWide += len(p[1])

numNodesInDeep = 0
for paramName, paramVect in deepnet.named_parameters():
    if 'bias' in paramName:
        numNodesInDeep += len(paramVect)

print("Wide:", numNodesInWide)
print("Deep:", numNodesInDeep)

Wide: 7
Deep: 7


In [7]:
nparams = 0
for p in widenet.parameters():
    if p.requires_grad:
        print('Parameters: ', p.numel())
        nparams += p.numel()

print("Total: ", nparams)

Parameters:  8
Parameters:  4
Parameters:  12
Parameters:  3
Total:  27


In [9]:
nparams = np.sum([p.numel() for p in widenet.parameters() if p.requires_grad ])
print("widenet: ", nparams)

nparams = np.sum([p.numel() for p in deepnet.parameters() if p.requires_grad ])
print("Deepnet: ", nparams)

widenet:  27
Deepnet:  21


In [18]:
from torchsummary import summary

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
widenet.to(device)

summary(widenet, (1,2))

----------------------------------------------------------------
        Layer (type)               Output Shape         Param #
            Linear-1                 [-1, 1, 4]              12
            Linear-2                 [-1, 1, 3]              15
Total params: 27
Trainable params: 27
Non-trainable params: 0
----------------------------------------------------------------
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00
----------------------------------------------------------------
